name: Build Store

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build with OpenOrbis Action
      uses: OpenOrbis/toolchain-action@main
      with:
        version: v0.5.2
        command: cd Store && make

    - uses: actions/upload-artifact@v4
      with:
        name: FreeWarGamer-Store
        path: Store/*.pkg
